// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://csklrgutxvcdqlnwnlvt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNza2xyZ3V0eHZjZHFsbndubHZ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwOTA3MjYsImV4cCI6MjA1OTY2NjcyNn0.UZjKAUWzQqr7EscqaCKkd9k0HtzYGnWMVY8WTdrKlFE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);